project:
  type: book
  output-dir: docs

book:
  title: "Curso de Python"
  subtitle: "para Análise de Dados"
  author:
    name: "Breno Cauã Rodrigues da Silva"
    orcid: 0009-0005-9740-2069
    corresponding: true
    affiliations:
      - name: "Centro Acadêmico de Estatística"
      - name: "Faculdade de Estatística"

  page-footer:
    left: |
      **SILVA, B.C.R**
    right: |
      Construído <a href="https://quarto.org/"> Pacote Quarto no R4.3</a>.
  repo-url : https://github.com/csilv7/PYTHON_COURSE_FOR_DATA_ANALYSIS
  repo-subdir: docs
  repo-branch: main
  repo-actions: edit #[edit, issue, source]
  sharing: [twitter, facebook]
  page-navigation: true
  chapters:
    - index.qmd
    - BASIC_CI.qmd
    - BASIC_CII.qmd
    - BASIC_CIII.qmd
    - MODULES.qmd

comments:
  hypothesis: true

format:
  html:
    number-sections: true
    code-fold: true
    code-tools: true
    code-link: true
    toc-title: Índice
    toc-location: right
    #fontcolor: "black"
    #theme:
    #  light: [blue, custom.scss]
    #  dark:  [cyborg, custom.scss]
    #theme: "lux"
    theme:
      light: [lux, custom.scss]
      dark:  [cyborg, custom.scss]
    highlight-style: monokai
    df-print: paged

execute:
  echo: true

lang: pt