project:
  type: book
  output-dir: docs

book:
  title: "Curso de Python"
  subtitle: "para Análise de Dados"
  author:
    name: "Breno Cauã Rodrigues da Silva"
    orcid: 0009-0005-9740-2069
    corresponding: true
    affiliations:
      - name: "Centro Acadêmico de Estatística"
      - name: "Faculdade de Estatística"

  page-footer:
    left: |
      **SILVA, B.C.R**
    right: |
      Construído <a href="https://quarto.org/"> Pacote Quarto no R4.3</a>.
  repo-url : https://github.com/csilv7/PYTHON_COURSE_FOR_DATA_ANALYSIS
  downloads: pdf
  repo-subdir: docs
  repo-branch: main
  repo-actions: edit #[edit, issue, source]
  sharing: [twitter, facebook]
  page-navigation: true
  chapters:
    - index.qmd
    - Módulo I\01_Fundamentals_of_Python.qmd
    - Módulo I\02_Data_Structure.qmd
    - Módulo I\03_FlowControl_&_Functions.qmd
    #- Módulo I\04_Exercises.qmd
    - references.qmd

comments:
  hypothesis: true

format:
  html:
    number-sections: true
    html-math-method: katex
    code-fold: true
    code-tools: true
    code-link: true
    toc-title: Índice
    toc-location: right
    theme:
     light: [blue]
     dark:  [cyborg]
    df-print: paged
    
  pdf:
    documentclass: scrreprt
    fig-pos: "H"
    number-sections: true
    pdf-engine: xelatex
    indent: true
    header-includes: |
      \usepackage{indentfirst}
    fontsize: 11pt
    geometry: [left=2cm, top=2cm, right=2cm, bottom=2cm]

bibliography: references.bib

execute:
  echo: true

lang: pt